stages:
  - maventry
  - maventest
  - mavendeploy


maven-build:
  stage: maventry
  tags:
    - springboot_tag 
  script:
    - cd Backend
    - cd Spring
    - mvn clean package

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - cd Spring
    - mvn test
