# Example  .gitlab-ci.yml file
stages:
  - maventry
  - mavendeploy

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - nathan_backend_tag  					# this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - cd Spring #change directory to where you have your springboot application
    - mvn package

maven-deploy:
  stage: mavendeploy
  tags:
    - nathan_backend_tag
  script:
    - cd Backend/Spring
    - mvn package
    - sudo mv target/*.jar /target/code42.jar
    - sudo systemctl stop system-code42
    - sudo systemctl start system-code42
    
