stages:
  - maventry
  - mavendeploy


maven-build:
  stage: maventry
  tags:
    - springboot_tag 
  script:
    - cd Backend
    - cd Spring
    - mvn clean package

maven-deploy:
  stage: mavendeploy
  tags:
    - springboot_tag
  script:
    - cd Backend/Spring
    - mvn package
    - sudo mv target/*.jar /target/code42.jar
    - sudo systemctl stop system-code42
    - sudo systemctl start system-code42
    
